### ISSUE TITLE
Enhancement: Add a CLI

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#151]
We should consider adding a CLI that will allow users to quickly scaffold a project with a default folder / file structure, readme, tooling etc. 

A good example is the NestJS CLI. 

I'd like to discuss this proposal in this issue.

**Comment by peterschutt** [comment]
`poetry new` is the first example that stands out to me. They have [cleo](https://github.com/python-poetry/cleo.git).

**Comment by vrslev** [comment]
> We should consider adding a CLI that will allow users to quickly scaffold a project with a default folder / file structure, readme, tooling etc.

I think it is a great idea in context of Starlite project.

> A good example is the NestJS CLI.

I really like the one that Vue 3 has: https://vuejs.org/guide/quick-start.html#local. Very powerful yet approachable.

**Comment by Goldziher** [comment]
Ok. So, let's talk about structure-

Given that you probably want to install a CLI as as a global executable outside your project, I think it might be a good idea to separate it out into its own package and publish it separately. I know sometimes the CLi is a part of the app, but I think here it's going to be an issue - the CLI should be independent from the starlite version IMO. 

We should consider whether we want to split it to a different repo, or simply a folder in this repo. 

Pros of different repo:

1. Separation of concerns
2. No shared dev dependencies
3. Simpler release process
4. No need for a monorepo or similar construct

Cons:

1. A separate code base might make it harder to contribute, e.g. issues etc. 
2. Stars are spread across repos.  
3. No code sharing is possible (no biggy on this case)

**Comment by vrslev** [comment]
Is there anything similar to [`npm init`](https://docs.npmjs.com/cli/v8/commands/npm-init#examples) in Python world? Maybe just [`cookiecutter`](https://github.com/cookiecutter/cookiecutter)?

**Comment by JeromeK13** [comment]
What about using cookiecutter together with clap?
So you could create a separate repo for the template but still integrate the cli into the "main" repo while using cookiecutter as a base.

**Comment by Goldziher** [comment]
I'm open to this idea. I have no experience working with these tools tbh.

**Comment by JeromeK13** [comment]
Alright I could do a proposal. In general do you care about dependencies in this project?
For example is it a problem for using Clap instead of the default arg-parser?

**Comment by peterschutt** [comment]
Would it also mean `cookiecutter` was a dependency of the standard install?

**Comment by Goldziher** [comment]
It will be an `extra` dependency I assume, so it shouldnt be a problem.

**Comment by Alex-CodeLab** [comment]
What would be a good project-structure?
I think something like this:

```
src                           # project root  
├── admin-cli.py
├── main.py         
├── /config           # project configuration 
│      ├── /settings   
│      │     ├── base.py   # project settings   
│      │     ├── local.py   # local settings 
│      │     ├── prod.py   # production settings 
├── /my_app     
│      ├── controller.py
│      ├── model.py
│      ├── /tests

```
Easiest would be to include the folderstructure as some template, or have it in a zip.
The files itself could contain `{{variables}}` , which can be replaced using `jinja2`.

**Comment by Goldziher** [comment]
> What would be a good project-structure? I think something like this:
> 
> ```
> src                           # project root  
> ├── admin-cli.py
> ├── main.py         
> ├── /config           # project configuration 
> │      ├── base.py   # project settings   
> │      ├── local.py   # local settings 
> │      ├── prod.py   # production settings 
> ├── /my_app     
> │      ├── controller.py
> │      ├── model.py
> │      ├── /tests
> ```
> 
> Easiest would be to include the folderstructure as some template, or have it in a zip. The files itself could contain `{{variables}}` , which can be replaced using `jinja2`.

cookie-cutter is a good option for generation. 

As for the structure - I think @cofin and @peterschutt have some opinions there.

**Comment by Alex-CodeLab** [comment]
> cookie-cutter is a good option for generation.

cookie-cutter is nice, but then it can only do one thing: build a project-structure.
Cookie-cutter does more or less the same: take a template folderstructure, and search/replace with Jinja, and copy it to some destination.

When I read `cli`,  I think of a command-line application that could be extended with new commands as well.
For example, in Django there are about 20 commands (`startproject`, `startapp`, `clear_cache`, `create_superuser`,... ), and each module can easily add new ones. (Such a `cli` could even call cookiecutter in the background if you really want to use that )

**Comment by john-ingles** [comment]
Cookiecutter can also run pre and post-generation callbacks but it would probably be best to call cookiecutter instead of having it do the calling

**Comment by Goldziher** [comment]
I dont have a strong opinion one way or the other - whatever works best.

**Comment by Goldziher** [comment]
Assigning this to myself

**Comment by Goldziher** [comment]
Ok, so for the CLI we need to flush out some requirements before we proceed. I will be closing this issue and create a discussion instead.

**Comment by provinzkraut** [comment]
Reopening this because of popular demand

**Comment by provinzkraut** [comment]
## Todo

- [x] Basic CLI framework
- [ ] CLI commands
    - [x] Running an application
    - [x] Application autodiscovery
    - [x] Routing table overview
    - [ ] Scaffold new application / project
- [ ] Project template (cookiecutter) including feature selection / configuration for:
    - Plugins (ORM integrations) 
    - Logging
    - Caching
    - Sessions
    - Middlewares
    - Templates
    - Static files
- [x] Utils to register commands dynamically

**Comment by provinzkraut** [comment]
After experimenting with the CLI, and trying it out as a separate package I've come to the conclusion that it's not necessary or desirable for the following reasons:

Publishing it as a standalone package means that it should not have a hard dependency on Starlite. This also means
 that every code that interacts with Starlite needs to be imported within the commands that use it, leading to quite a bit
of messy code. You can see this [here](https://github.com/starlite-api/starlite-cli/blob/e0b0867eab635c94cdd4dd6ef470f23d329bd202/starlite_cli/main.py)

This decoupling also means that there's effectively only one command that's going to be usable when invoked outside of an already existing Starlite project: The command to create a new Starlite project. 

Since there is only one command that doesn't depend on a Starlite installation (i.e. doesn't interact with an application instance) I think moving forward it makes most sense to publish a separate utility for **this command**. It really is its own thing and has, neither conceptually, code or usage wise, anything to do with the rest of the CLI. I propose we create a `create-starlite-app` package, that can simply be run e.g. with `pipx run create-starlite-app` and include the CLI parts that interact with an existing application with the regular `starlite` package.

This approach also means less dependencies required for each package (the only dependency they'd have in common would be `click`), which is always a nice thing and we could potentially include the CLI by default instead of an extra.
