### ISSUE TITLE
Documentation: Reference docs WIP tracking issue

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#341]
This issue is for tracking work still to be completed for rollout of the reference api docs.

**Comment by peterschutt** [comment]
The following reference doc pages are incomplete (relative to `docs/reference/`):

- [ ] `app.md` - include `DEFAULT_CACHE_CONFIG` and cross-ref in `Starlite.__init__` args
- [ ] `cache.md`
    - [ ] `CacheBackendProtocol` - add abstract methods
- [ ] `config.md` - fix ordering so same as module
- [ ] `connection.md`
    - [ ] `Request` - docstrings for properties, include properties and `json()` method
    - [ ] `WebSocket` - docstrings for properties, include properties and `receive_json()` and `send_json()` methods
    - [ ] consider factoring out a common `Connection` base class with the properties defined and documented.
 - [ ] `controller.md` - complete `__init__` docstring and include `__init__` and `get_route_handler()`
 - [ ] `datastructures.md` - document and include all
 - [ ] WIP... more  to come...

**Comment by Goldziher** [comment]
well two of these are done 😉

**Comment by peterschutt** [comment]
Other things TODO:

- [ ] update the contributing docs with instructions for reference docs as part of contributions
- [ ] change instructions in `CONTRIBUTING.md` for serving docs locally - the docker approach won't work unless we run our own container with the extra dependencies, or find one to use. `mkdocs serve` has been working fine for me.
- [ ] remove the WIP admonition once complete
- [ ] once all interfaces are included, do a final sweep to look for missing cross-references.

**Comment by peterschutt** [comment]
This is wrong: 
https://github.com/starlite-api/starlite/blob/db1eab98c50c1ed9fa176e7e06c3b34ddee68197/starlite/app.py#L123-L125

**Comment by peterschutt** [comment]
Documented in wrong location:

https://github.com/starlite-api/starlite/blob/db1eab98c50c1ed9fa176e7e06c3b34ddee68197/docs/reference/enums.md?plain=1#L15-L19

It's defined in `config.py`
