### ISSUE TITLE
Documentation: Improve Documentation

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#421]
This is a "standing" refactor ticket. Contributors are welcome to add PRs addressing it, and it is as such a good place to start contributing to the project. PRs addressing any of the following are welcome:

1. Edit and improve the documentation language.
2. Add / improve examples.
3. Write and improve references (using docstrings in code and linking to the references section)
4. Improve the mkdocs site by any of the following: improving CSS, updating setup and plugins, improving UI / UX, updating icons and graphics.
5. Create better logos, repository social cards etc. for Starlite.

Additionally, we welcome any write-ups and blogs posts about the framework - and will gladly link to them in our docs as well as add attributions using `all-contributors`

**Comment by provinzkraut** [comment]
The current plan of attack would look a little something like this:

1. **Examples**  (#343)
    - [ ] Extract all inline-examples from the docs that are more than snippets
    - [ ] Ensure all examples are self-contained and runnable
    - [ ] Ensure all examples are tested
    - [ ] Ensure all examples work on the minimal supported Python version (3.7)
    - [ ] Add alternative examples for higher python versions (can be automated in the build step I think)
2. **Tutorials**
    - [ ] Full step-by-step application tutorial, covering all basic topics, requiring no prior knowledge
    - [ ] Tutorials covering more specific topics (caching, advanced integration, etc.)
3. **Usage**
    - [ ]  Remove tutorial-like sections from "Usage" docs, make them more terse on basics and more in-depth on the technical side
    - [ ] Improve legibility / style of text passages so they have a somewhat coherent writing style (we should come up with some general guidelines for this)
4. **Reference**
    - [ ]  Show inherited members (#427)
    - [ ] Make all docstrings of public interfaces adhere to the same style (#776)
    - [ ] Enforce the docstring style with a pre-commit hook (#776)
