### ISSUE TITLE
Documentation/Meta: API stability policy

### ISSUE THREAD

**Issue by provinzkraut** [starlite-api/starlite#867]
Following the discussion in #848, this issue seeks to track the process of implementing the discussed policy.

# TODO

- [ ] Craft a document describing the specifics of our API stability/deprecation policy
- [ ] Update deprecation utilities to the new requirements
- [ ] Create a developer guideline for deprecations
- [ ] Integrate the deprecation process with current tooling (i.e. linting stage, automated notes in documentation)
- [ ] Integrate the changelog into the docs, include "migraton guide" for breaking changes

**Comment by Kd-Here** [comment]
Hey @provinzkraut did you updated all the info in documentation.
If not can you help me
**I am learning how to write techincal documentation it will a good training for me.**

**Comment by provinzkraut** [comment]
No, this isn't done yet, hence this issue still being open.

If you want to give it a shot, go ahead. If you need help, I recommend reaching out on our discord. I'm still away at the moment for Christmas, but I'll be able to review it / give input once I'm back.

**Comment by provinzkraut** [comment]
Completed by #1131
