### ISSUE TITLE
Enhancment: Adding a CLI

### ISSUE THREAD

**Issue by provinzkraut** [starlite-api/starlite#973]
# Starlite CLI

Discussed in https://github.com/starlite-api/starlite/discussions/603
Current draft PR: #936 

## Todo

- [x] Basic CLI framework
- [ ] CLI commands
    - [x] Running an application
    - [x] Application autodiscovery
    - [x] Routing table overview
    - [ ] Scaffold new application / project
- [ ] Project template (cookiecutter) including feature selection / configuration for:
    - Plugins (ORM integrations) 
    - Logging
    - Caching
    - Sessions
    - Middlewares
    - Templates
    - Static files
- [x] Utils to register commands dynamically
- [ ] Publish CLI as a separate package (see [this comment](https://github.com/starlite-api/starlite/discussions/603#discussioncomment-4409281) for an explanation)

**Comment by provinzkraut** [comment]
Closed and moving to #151
